"""Initial migration

Revision ID: 1b6ebdd051d6
Revises:
Create Date: 2026-08-23 18:45:58.266153

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b6ebdd051d6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("profile_pic_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "ADMIN", "TRAINER", "SALES_MANAGER", "HOA", "AGENT", name="userrole"),
            nullable=False,
        ),
        sa.Column("employee_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("branch_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("territory", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("specializations", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("agent_code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("sm_id", sa.Uuid(), nullable=True),
        sa.Column("hoa_id", sa.Uuid(), nullable=True),
        sa.Column("date_appointed", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_password_changed", sa.Boolean(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_password_change_at", sa.DateTime(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hoa_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sm_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_agent_code"), "users", ["agent_code"], unique=True)
    op.create_index(op.f("ix_users_branch_id"), "users", ["branch_id"], unique=False)
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_employee_id"), "users", ["employee_id"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "otps",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("hashed_code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("LOGIN", "PASSWORD_RESET", "EMAIL_VERIFICATION", name="otppurpose"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otps_created_at"), "otps", ["created_at"], unique=False)
    op.create_index(op.f("ix_otps_expires_at"), "otps", ["expires_at"], unique=False)
    op.create_index(op.f("ix_otps_hashed_code"), "otps", ["hashed_code"], unique=False)
    op.create_index(op.f("ix_otps_is_active"), "otps", ["is_active"], unique=False)
    op.create_index(op.f("ix_otps_purpose"), "otps", ["purpose"], unique=False)
    op.create_index(op.f("ix_otps_updated_at"), "otps", ["updated_at"], unique=False)
    op.create_index(op.f("ix_otps_user_id"), "otps", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("refresh_token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("device_type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_access_token_hash"), "sessions", ["access_token_hash"], unique=False)
    op.create_index(op.f("ix_sessions_created_at"), "sessions", ["created_at"], unique=False)
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_is_active"), "sessions", ["is_active"], unique=False)
    op.create_index(op.f("ix_sessions_refresh_expires_at"), "sessions", ["refresh_expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_refresh_token_hash"), "sessions", ["refresh_token_hash"], unique=False)
    op.create_index(op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_updated_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_is_active"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_access_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_otps_user_id"), table_name="otps")
    op.drop_index(op.f("ix_otps_updated_at"), table_name="otps")
    op.drop_index(op.f("ix_otps_purpose"), table_name="otps")
    op.drop_index(op.f("ix_otps_is_active"), table_name="otps")
    op.drop_index(op.f("ix_otps_hashed_code"), table_name="otps")
    op.drop_index(op.f("ix_otps_expires_at"), table_name="otps")
    op.drop_index(op.f("ix_otps_created_at"), table_name="otps")
    op.drop_table("otps")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_employee_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_users_branch_id"), table_name="users")
    op.drop_index(op.f("ix_users_agent_code"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
